# The Historical Context of Contemporary International Relations

Why do we care about history? It is because history explains the origins of key concepts in international relations such as sovereignty, the international state system, colonialism, and power distribution among states. Throughout modern history, four distinct changing movements have occurred: democratization, modernization, secularization, and globalization.

+ Democratization: Many states in modern history have experienced regime transitions from authoritarian to democratic. Samuel Huntington, for example, refers to the three major regime transition movements as "waves."

+ Modernization: It encompasses various aspects of societal development, including education, economic growth, and human rights.

+ Secularization: The political power of the church no longer trumps the political power of the states. After a 30-year war, kings were free of the Pope.

+ Globalization: The world's increasing integration in terms of politics, economics, and culture. Financial markets are intertwined, and states are culturally homogenizing.

## Remarkable Events

### Thirty Year's War (Westphalian system)
#### Description

A religious dispute between Catholics and Protestants. It began when Holy Roman Emperor Ferdinand II of Bohemia attempted to curtail the religious  activities of his subjects, sparking rebellion among Protestants.

#### Significance
+ Most international relations theorists locate the origins of the contemporary state system in Europe in 1648, the year the Treaties of Westphalia ended the Thirty Years’ War. 

+ These treaties marked the end of rule by religious authority in Europe
and the emergence of secular authorities. With secular authority came the principle that has provided the foundation for contemporary international relations: the notion of the territorial integrity of states.

### American and French revolutions (1773–85, 1789)

### Napoleonic Wars (1803–15)
#### Description
Napoleon led large, well-armed, and passionately motivated armies to conquer the entire Europe.

#### Significance
In combination with nationalism, advanced system made it possible for the French to field larger, more mobile, and more reliable armies that could employ innovative tactics.

### The Concert of Europe
#### Description
General consensus among the Great Powers to maintain the European balance of power and the integrity of territorial boundaries.

#### Significance
The concert of Europe made the balance of power be rule of thumb for the European countries for their foreign policy goals.

### Solidification of Alliances and World War I

Whereas in most of the nineteenth century, alliances had been flexible and fluid, by the later years, alliances became more rigid. The balance of power broke down due to these solidifications of alliances, resulting in World War I.

### World War II

+ Hitler and the **Third Reich**: Fascism as practiced by Hitler effectively mobilized the masses in support of the state, exalting the nation and race above the individual. It capitalized on the idea that war and conflict were noble activities from which ultimately superior civilizations would be formed. 

+ The rise of Mussolini and fascist Italy

+ Brutality of the Axis powers toward noncombatants

### The Cold War

After World War II, the United States and the Soviet Union (USSR) emerged as two superpowers. The Cold War describes about 45 years of overall high-level tension and competition between the superpowers but no direct military conflict.


+ The United States adopted a policy of **containment**, as opposed to a more aggressive **rollback** strategy.

+ The USSR pushed favored an aggressive rollback strategy, which forces other countries to change their policies.

## Key Concepts
### Sovereignty
#### Description
Independent legal authority over a population in a particular territory, based on the recognized right to self-determination. 

#### Significance
Sovereignty rests with those who have the ultimate right to make political decisions.

### Balance of Power
#### Description
States with relatively equal power offset concentrations of power to prevent the emergence of hegemonies or hegemonic blocks.

#### Significance
+ When one state or coalition of states is much more powerful than its adversaries, asymmetrical war is relatively more likely.

+ Due to BoP, states considered multipolar system is likely to lead stable international system.

