# The Tools of Statecraft
## The State, Defined

+ Stable population

+ An effective government to which the population has allegiance

+ Recognized diplomatically by other states

## State Power
Power is the ability to influence behavior and control outcomes. States’ ability to get others to do something that they would not otherwise do. All theoretical perspectives acknowledge the importance of power, but each pays attention to different types of power. 

  + Realists and liberals conceptualize power in materialist terms. 
  
  + Constructivists emphasize nonmaterialist sources.

## Hard Power versus Soft Power
### Hard power
It entails using various sources of power to coerce others. States using various sources of power (economic or military) to coerce other states into adopting actions in its interests.

### Soft power
It entails trying to persuade others. The power to attract states to change their behavior rather than having to coerce them into doing so; power is based on the legitimacy of the state’s values or its policies.

### Smart power
Successful power projection often involves a combination of both hard and soft power.

## Statecraft
### Diplomacy
#### Track One diplomacy
##### Traditional diplomacy

+ Influencing the behavior of others by negotiating and bargaining

+ Taking a specific action or refraining from action

+ Appealing to the foreign public for support of a position

##### Public diplomacy


+ Involves strategically targeting foreign publics and elites with informational, cultural, and educational programming.

+ Important use of a country’s soft power

#### Track Two diplomacy
Nofficial overtures by private individuals or groups from outside governments to try and resolve an ongoing international crisis or civil war. The idea behind this type of diplomacy is that the absence of government officials who are supposed to defend their government’s policy positions might lead to more open discussions with a greater likelihood of breaking through difficult impasses. 



### Economic statecraft
#### Positive sanctions

Carrots” entice states to move in the desired direction, assuming that positive incentives will lead the target state to change its behavior.

  + Granting trading privileges
  
  + Permitting trading in sensitive products
  
  + Giving corporations investment guarantees or tax breaks 

#### Nagative sanctions

Threaten or take actions that punish the state for an undesirable move.

  + Freeze a target state’s assets.
  
  + Prohibit certain financial transactions.
  
  + Arms embargoes
  
  + Comprehensive sanctions 
  
  + Allowing importation of goods at best rates

#### Smart sanctions

Targeted sanctions focusing on specific individuals and groups to avoid the high humanitarian costs of general sanctions. Limited sanctions targeted to hurt or support specific groups; used to avoid the humanitarian costs of general sanctions.

+ Smart sanctions are seen as a cheaper option than general sanctions.

+ Sometimes, sanctions can have unintended negative consequences.

### Force
#### Compellence

Threat of the use of force to get a target state to do something or undo an act already undertaken.

#### Deterrence

Threatening or actually punishing a target state if it takes an undesired action



