# Human Rights
## What Are the Human Rights?

Each one of us no matter who we are or where we are born is entitled to the same basic rights and freedoms.

+ Human rights are not privileges.

+ Human rights cannot be granted or revoked.

+ Human rights inalienable and universal.

## Basic Concepts

### Political and civil human rights

+ Rights that states cannot take away (free speech, assembly)

+ Freedom of speech and assembly, security, and protection of the press

+ No individual should be deprived of these rights.

+ Enshrined in historical documents, such as

  + The Magna Carta, 1215

  + The French Declaration of the Rights of Man, 1789

  + U.S. Bill of Rights, 1791


### Economic and social human rights

+ Rights that states should provide (health care, jobs)

+ Decent education, work, health care, and standard of living

+ Rights with a focus on “the material”

+ Heavily influenced by Karl Marx’s writings and critical social theorists

  + Socialist theorists believe that without these guarantees of socioeconomic rights, political and civil rights are meaningless.

### Collective rights

+ The rights of the marginalized

+ The idea of collective rights is not nearly as universal as these rights are contested within states.

+ Broad spectrum of rights that states should provide to minorities and the historically marginalized as well as to the collective:

  + Consist of rights for refugees, ethnic minorities, women, indigenous peoples, and LGBTQ+ individuals

  + Include the right to development and the right to a clean environment

+ Highly contested in states and the international arena

## Human Rights as Emerging International Responsibility

Geneva Conventions form the core of international humanitarian law.

+ I: protection of the wounded in the armed forces (1864)

+ II: protection of the wounded at sea (1906)

+ III: protection of prisoners of war (1929)

+ **IV: protection of noncombatants during wartime (1949)**

Geneva Conventions form the core of international humanitarian law. Slow evolution (almost 80 years!) of human rights until World War II. Contrary to popular belief, the Geneva Conventions do not prohibit the use of weapons of mass destruction. Because the Geneva Conventions are concerned with the protection of human rights. The Hague Convention and the Geneva Protocol govern weapons of mass destruction (related to biological and chemical weapons).

+ UN Universal Declaration of Human Rights, 1948

  + A statement of human rights aspirations; Though not legally binding, the statement identified 30 human rights principles covering both political and economic rights. 

+ Two legally binding documents

  + The International Covenant on Economic, Social, and Cultural Rights

  + The International Covenant on Civil and Political Rights

+ These three documents are known as the International Bill of Rights. 

### Two-faced States: States as Protectors of Human Rights

Westphalian tradition suggests that states are primarily responsible for protecting human rights standards within their own jurisdiction. Many liberal democratic states support political and civil rights in their foreign policy. Using diplomacy by tying certain benefits to improvements in human rights.

+ Offering trade concessions or increased aid

+ Punishing through sanctions 

+ Example studied: Kim and Kroeger (2017) Rewarding the introduction of multiparty elections. *EJPE*

### Two-faced States: States as Abusers of Human Rights

Authoritarian or autocratic states are more likely to abuse political and civil rights. Less developed states may be unable or unwilling to meet basic obligations of social and economic rights due to scarce resources or lack of political will. State security often prevails over individual rights. Political-civil rights may be repressed in times of economic strife to divert attention from the economy. Culture and history affect a state’s human rights record.

## The Role of the International Community—IGOs and NGOs

+ Set human rights standards (United Nations)

+ Monitor standards

+ Establish complaint procedures

+ Compile reports on state behavior

+ Investigate alleged violations

IGOs may, at times, respond to egregious humanitarian emergencies (United Nations, states). 

+ In a few cases, states may use IGOs to respond to egregious humanitarian emergencies.
  
+ So-called humanitarian intervention was used in the crisis in Somalia in 1992.

### Naming and shaming

Publicly identifying and stigmatizing the non-compliant actors

+ NGO’s weapon against repressive regimes

+ State - primarily targets or supporters of naming and shaming (passive roles)

### Enforcement Problems

A state’s signature on treaties is no guarantee of its willingness or ability to enforce treaty provisions. Monitoring via self-reporting presumes a willingness to comply and be transparent. NGOs play a key role in monitoring. Economic embargoes may not achieve changes in human rights policy and may hurt those whom embargoes are intended to help. Military action may cause unintended casualties.

Does monitoring by IGOs or NGOs through investigations, reports, resolutions, and naming and shaming ultimately make a difference for rights protection? The evidence is mixed. One study of over 400 human rights organizations on shaming governments between 1992 and 2004 found that states targeted by NGOs do improve their human rights practices. But shaming is not enough. Shaming is effective when both domestic NGOs on the ground and advocacy by other third parties and individuals are present. 

### Specific Human Rights Issues: Genocide and Mass Atrocities

**Crimes against humanity**: Article 7 of the Rome Statute of the International Criminal Court

+ In 2021, the Trump administration, echoed by the Biden administration, labeled the Chinese government as committing genocide against the Uighurs and other minority groups. 

+ This designation is controversial given conflicting interpretation of what constitutes genocide and whether that designation then puts pressure on states and the international community to take action to stop the systematic abuse.

### Punishing the Guilty

International Criminal Court (ICC) covers four types of crimes: genocide, crimes against humanity, war crimes, and crimes of aggression.

+ No individuals are immune from jurisdiction, including heads of states and military leaders.

+ Many African heads of state feel unfairly targeted by the ICC.

+ Some states, including the United States, feel that ICC impinges on state sovereignty and refuse to sign the treaty.

+ While many supporters see the court as essential for establishing international law and enforcing individual accountability, the short-term impact has not been positive. 

+ Critics see the failure of the ICC to investigate China’s actions against the Uighurs as a vast moral failure. 

### The Globalization of Rights: Women’s Rights as Human Rights

The UN reports that violence against women and girls “persists at alarmingly high levels.” 

Post–World War II emphasis on political and civil rights 

1960s–1970s: increasing concern for economic rights

+ Women in development movement (WID)

+ UN-sponsored conferences on women

While NGOs and IGOs attempt to combat the problem, the mainstay of enforcement continues to be at the state level. The best statistical predictor of state peacefulness is not democracy or wealth but the level of physical security for women. The higher the level of violence against women, the more likely the state is involved in interstate and intrastate conflict.

### The Debate Over Humanitarian Intervention and R2P

Military action to stop massive violations of human rights may be just and necessary (humanitarian intervention). 

+ Contradicts and erodes the Westphalian view of state sovereignty

+ Why do we see selective bias?

  + In the nineteenth century, Europeans used military force to protect Christians in Turkey and the Middle East, though they chose not to protect other religious groups. 
  
  + And European nations did not intervene militarily to stop slavery, though they prohibited their own citizens from participating in the slave trade. 

**Responsibility to protect (R2P)**: in cases of massive violations of human rights, when domestic avenues for redress have been exhausted, states have a responsibility to intervene.

+ How massive do the violations have to be?

+ Are UN Security Council authorizations necessary? 

+ Could states have ulterior motives? 

## Article: BDM et al. (2005) Thinking Inside the Box

BDM et al. (2005) argues that a gradual, continuous democratization process does not lead to a gradual improvement of human rights. Some aspects of democratization process generate higher level of human rights protection. Thus, BDM et al. (2005) expects that increasing degrees of democracy do not lead smoothly to improved human rights; rather, it depends on the mix of scores on the various dimensions that compose a particular scale. Democracy is reliable as a means of reducing human rights abuses only when institutional reforms pass thresholds that ensure accountability, thereby translating institutional changes into behavioral changes. BDM et al. (2005) finds that democratization does not yield significant improvements for human rights until party competition is normalized. Human rights improvements reflect the discontinuous function of democratization. They conclude that multiparty competition is more significant than other dimensions to reduce human rights abuses. Increases at a state level of democracy do not generate greater respect for human rights. Fully democratization significantly improves human rights record.

> At least read abstract.

## Article: Park et al. (2019) The (co)evaluation of human rights advocacy

Park et al. (2019) answers the question of how human rights issues change over time. They argues that advocates adopt issues similar to their existing agenda. Resource limitation led organizations to adopt issues that can earn much attention. Testing with quantitative text analysis, previously identified distinct latent topics may combine together as they being discussed together by human rights organizations. Park et al. (2019) concludes that human rights issues evolve over time and shows that human rights issues are interdependent with each other and co-evolve over time.

> At least read abstract.

