# Final Exam Pool {-}

## Part I. Multiple-Choice {-}

I will update it after the 6th pop quiz.

----

1. The textbook distinguishes between the types of dictatorships based on:

    A. size of the country

    B. title of the leader

    C. identity of their support coalitions

    D. type of election

2. The three basic types of authoritarian regime outlined in the textbook include all of the following EXCEPT:

    A. monarchies.

    B. oligarchies.

    C. military.

    D. civilian.
    
3. Presidents are

    A. never have term limits.

    B. are more likely to have term limits than prime minister.

    C. are less likely to have term limits than prime minister.

    D. are equally as likely to have term limits as prime minister are.

4. What is (are) the key difference(s) between majoritarian and proportional representation (PR) electoral systems?

    A. In majoritarian systems, the winning candidate(s) must win a majority or plurality of the vote, whereas this is not necessary in PR systems.

    B. PR systems use large district magnitudes or two-round systems in single districts to elect candidates.

    C. All of these are differences between majoritarian and PR systems.
    
5. In countries with semi-presidential systems

    A. the president is elected directly by voters.

    B. the prime minister and the president are directly elected by the voters

    C. the prime minister is elected directly by voters.

    D. the president is elected by the Parliament.

6. An overview of a variety of studies about the link between regime type and economic growth should lead one to the following conclusion:

    A. Democracy is better for growth than dictatorship.

    B. Dictatorship is better for growth than democracy.

    C. Regime type makes no difference.

    D. There are some empirical studies that support each of the conclusions listed in (a)–(c), above. In part, this variation in conclusions is likely to be the result of the different datasets used across the analyses.

7. Those dictators that hold elections and tolerate some degree of pluralism yet violate democratic standards are called: 

    A. electoral authoritarian.
    
    B. democratic pluralism.
    
    C. liberal democracy.
    
    D. pluralist dictatorship.

8. In the country of Qatar, the successor to the king is selected by the ruling family by consensus based on their own best interests.  Based on this information, Qatar can be labeled a:

    A. monarchy.

    B. military dictatorship.

    C. dominant-party dictatorship.

    D. personalistic dictatorship.
    
9. Dictatorships that do not rely on either the support of the military or a ruling family or kin network are called:

    A. monarchies.

    B. military dictatorships.

    C. civilian dictatorships.

10. The most common form of dictatorship from 1946 to 2008 has always been:

    A. monarchies.
    
    B. military dictatorships.

    C. civilian dictatorships.

11. The Communist Party in the former Soviet Union is an excellent example of this type of regime:

    A. democracy.
    
    B. monarchy.
    
    C. military dictatorship.
    
    D. personalistic dictatorship.
    
    E. dominant-party dictatorship.

12. Dominant-party dictatorships rely on the following to stay in power:
    
    A. controlling the military.
    
    B. tying monetary and nonmonetary benefits to membership in the party.
    
    C. restricting the ability off opposition parties to effectively compete .
    
    D. only B and C.
    
    E. all of these.

13. Personalistic dictatorships are often characterized by which of the following?

    A. strong parties, strong militaries, and weak leaders

    B. free press, competitive elections, and multipartism

    C. weak press, strong secret police, and arbitrary uses of force

14. Personalistic dictators rely on ______ to maintain the loyalty of their support coalition and the citizenry more generally.

    A. cult of personality

    B. strong parties

    C. free media

    D. supportive military

15. The difference between hegemonic electoral authoritarian regimes and competitive authoritarian regimes is that:

    A. the former is where the major party wins only half the time and the latter is where the major party wins the vast majority of the time.
    
    B. the former is where the opposition parties win substantial minorities and the latter is where opposition parties often win in presidential elections.
    
    C. the former is where the leader’s party wins with overwhelming majorities and the latter is where the opposition parties win substantial minorities in elections.
    
    D. none of these

16. What is the basic assumption behind the selectorate theory?

    A. That dictators care more about staying in power than democratic leaders do.
    
    B. That dictators use elections to discourage internal rivals from attempting coups.
    
    C. That all political leaders are motivated by the desire to gain and maintain office.
    
    D. All of these are important assumptions of the selectorate theory.

17. According to BDM's Selectorate theory, what is the winning coalition?

    A. The party that wins.
    
    B. The government coalition that wins.
    
    C. The group of people who keep the leader in power.
    
    D. The group of people who can select the leader.
    
    E. The group of people who actually selected the leader.


18. If you were the leader, what type of institutions would you want to set up (assuming that you wanted to stay in power)?

    A. Institutions that would generate a small W and a small W/S.

    B. Institutions that would generate a small W and a large W/S.

    C. Institutions that would generate a large W and a large W/S.

    D. Institutions that would generate a large W and a small W/S.

19. If you were a member of the winning coalition, what type of institutions would you want to set up (assuming that you wanted to receive as many goods as possible)?

    A. Institutions that would generate a small W and a small W/S.

    B. Institutions that would generate a small W and a large W/S.

    C. Institutions that would generate a large W and a large W/S.

    D. Institutions that would generate a large W and a small W/S.

20. If you were a member of the selectorate but not the winning coalition, what type of institutions would you want to set up (assuming that you wanted to receive as many goods as possible)?

    A. Institutions that would generate a small W and a small W/S.
    
    B. Institutions that would generate a small W and a large W/S.
    
    C. Institutions that would generate a large W and a large W/S.
    
    D. Institutions that would generate a large W and a small W/S.

21. What set of institutions makes kleptocracy most likely?

    A. a large W/S and a small W
    
    B. a small W/S and a small W
    
    C. a large W/S and a large W

22. What is the fundamental implication of Arrow’s theorem?

    A. No alternative can beat the one preferred by the median voter in pair-wise majority-rule elections if the number of voters is odd, voter preferences are single-peaked over a single policy dimension, and voters vote sincerely.
    
    B. If there are two or more issue dimensions and three or more voters with preferences in the issue space who all vote sincerely, then it is likely (except in very extreme case) that there will be no Condorcet winner.
    
    C. There is no possible decision-making rule satisfying a minimal standard of fairness that is guaranteed to produce a rational decision for a group.

23. When we talk about “the government” in terms of distinguishing parliamentary, presidential, and semi-presidential systems (e.g., when we say that the government depends on the legislative majority as well as the president in a mixed system) we mean: 

    A. the state.
    
    B. all of the elected officials in a country.
    
    C. the cabinet (made up of the prime minister and the other ministers).
    
24. If the opposition in the legislature proposes a vote on whether or not the current government should stay in power, then this is an example of: 

    A. an investiture vote.
    
    B. a no confidence vote.
    
    C. a sincere vote.
    
    D. a strategic vote.

25. Which of the following statements best describes a vote of confidence?

    A. A new government must pass a vote (on the cabinet's composition and proposed policies) in the legislature before it can take office.
    
    B. A government declares that a vote on a particular piece of legislation is also a vote of support for the government itself; if the legislators do not support the legislation, then the government will resign (and new elections might result).
    
    C. A group of legislators propose a vote on the support of the incumbent government. If the government passes the vote, then it stays in office. If it fails the vote, then it must resign (and new elections might result).

26. In which system(s) is the government not responsible to the legislature?

    A. in a parliamentary regime
    
    B. in a presidential regime
    
    C. in a semi-presidential regime
    
    D. all of these
    
27. In which system(s) is the government responsible to the legislature but not the president?

    A. in a parliamentary regime
    
    B. in a presidential regime
    
    C. in a semi-presidential regime
    
    D. all of these

28. In which system(s) is the government responsible to the legislature and the president?

    A. in a parliamentary regime
    
    B. in a presidential regime
    
    C. in a semi-presidential regime
    
    D. all of these

29. In a semi-presidential regime, who is the primary political actor during periods of cohabitation?

    A. the president
    
    B. the prime minister
    
    C. Both, depending on the issue–prime minister has more control over domestic politics, but president still has a role in foreign policy.

30. If politicians are purely office seeking, what type of government would they prefer to form?

    A. connected coalition
    
    B. surplus majority government
    
    C. connected minimal winning coalition
    
    D. minimal winning coalition

    E. least minimal winning coalition

31. According to Lijphart (2012), which of the following is not correct to define joint-power dimension?

    A. Concentration of power in single-party majority cabinets versus executive power-sharing in broad multiparty cabinets.

    B. Executive-legislative relationships in which the executive is dominant versus executive-legislative balance of power.

    C. Flexible constitutions amendable by simple majority versus rigid constitutions amendable only by extraordinary majorities.

    D. Two-party versus multi-party systems

    E. Pluralist interest group systems with free-for-all competition among groups versus coordinated and “corporatist” interest group systems aimed at compromise and concertation.

32. According to Lijphart (2012), which of the following is not correct to define divided-power dimension?

    A. Unitary and decentralized government versus federal and decentralized government.

    B. Concentration of legislative power in a unicameral legislature versus division of legislative power between two equally strong but differently constituted houses.

    C. Majoritarian and disproportional electoral systems versus proportional representation.

    D. Legislatures that decide on the constitutionality of laws versus constitutional review by courts

    E. Central banks dependent on the executive that decide on the constitutionality of laws versus independent central banks.

33. Single-member district plurality (SMDP) systems are sometimes criticized because they:

    A. do not allow voters to hold their representatives accountable very easily.
    
    B. can produce very unrepresentative electoral outcomes at the district level.

    C. both (A) and (B) are common criticisms of SMDP systems.

34. Which type of party list gives the most power to the party leadership (over the individual candidates)?

    A. closed party list
    
    B. open party list
    
    C. free party list

35. What is a mixed electoral system?

    A. It is when the government depends on the legislature and the president.
    
    B. It is when you have districts that elect different numbers of people.
    
    C. It is when the electoral system uses both a majoritarian formula and a proportional formula.
    
    D. It is when you have multimember districts.
    
    E. It is when the winning candidate must win a majority or plurality of the vote.

36. The electoral system used for legislative elections (for the House of Representatives) in the United States is:

    A. single-member district plurality.
    
    B. two-round system.
    
    C. list PR.
    
    D. single nontransferable vote.

37. What is measured by “district magnitude”?

    A. the number of voters in a district
    
    B. the geographic size of the district
    
    C. the number of seats in a district
    
    D. the relative importance of the district

38. Which of the following is not correct for the main purposes of political parties?

    A. They structure the political world.

    B. They recruit and socialize the political elite.

    C. They mobilize the masses.
    
    D. They make politicians more diciplined and responsible.

    E. They provide a link between the rulers and the ruled.

39. Which of the following parties is correct for the blanks in the Figure below?

    A. (1) New politics party - (2) Party of mass integration - (3) Catch-all party - (4) Programmatic party - (5) Patronage-oriented party

    B. (1) Catch-all party - (2) Programmatic party - (3) Party of mass integration - (4) Patronage-oriented party - (5) New politics party

    C. (1) Catch-all party - (2) Programmatic party - (3) Patronage-oriented party - (4) Party of mass integration - (5) New politics party

    D. (1) Catch-all party - (2) Programmatic party - (3) Patronage-oriented party - (4) New politics party - (5) Party of mass integration



40. Imagine a country with an ethnically heterogeneous population. The different ethnic groups are geographically clustered so that if you consider particular areas of the country in isolation, they have relatively homogeneous populations. If such a country were to adopt a federal system, which type of federalism would you expect it to adopt?

    A. congruent and symmetric

    B. congruent and asymmetric

    C. incongruent and symmetric

    D. incongruent and asymmetric

41. According to the veto player theory, which following is not correct?

    A. Veto player theory shows that an increase in the number of veto players decreases the size of the winset or leaves it the same; it never increases the size of the winset.
    
    B. Veto player theory shows that an increasing the ideological distance between veto players always shrinks the size of the winset.

    C. When the winset is small, policy stability is low because there are more policy alternatives that can defeat the status quo.

    D. When the winset is large, the possibility arises for more radical shifts in policy.

42. In which of the following types of democracies would it be easier to change the current constitution?

    A. in a country with an entrenched constitution
    
    B. in a country with an unentrenched constitution

43. Veto player theory suggests that countries containing many veto players with conflicting policy preferences are likely to be characterized by:

    A. greater policy stability.
    
    B. smaller shifts in policy.
    
    C. less variation in policy shifts.
    
    D. weaker agenda-setting powers.
    
    E. all of these are characteristics likely to occur in such a situation.
    
44. The discussion of federalism contains a distinction between *de facto* federalism and *de jure* federalism. The latter is referred to as “federalism in structure.” To be classified as federal in structure, what features must a country have?

    A. A unitary state.
    
    B. Constitutionally regional governments that cannot be unilaterally abolished by the national government. Both the regional and the national government govern their own citizens directly, and both have independent bases of authority.
    
    C. A bicameral legislature, in which legislative deliberations occur in two distinct assemblies.

    D. devolution

45. Is the incentive to vote strategically higher or lower when the district magnitude is large?

    A. higher

    B. lower

    C. the same

## Part II. True/False Question {-}

I will update it after the 6th pop quiz.

----

1. Which policies are likely to be unpopular with the general public in the short term, those that promote immediate consumption (spending) or those that promote investment?

    A. Policies that promote immediate consumption.

    B. Policies that promote investment.

2. If a country has an independently elected president, then we necessarily consider it to be a presidential regime.

    A. True

    B. False
    
3. A one-party dominant system has only one legal party.

    A. True

    B. False
    
4. We can describe the property rights story for the relationship between democracy and economic growth as below:

    > "Democracies have higher economic growth because they are characterized by the rule of law and the protection of property rights."

    A. True
    
    B. False
    
5. Military dictatorships often claim the “guardians of the national interest:”

    A. True
    
    B. False
    
6. To stay in power, leaders must keep members of their winning coalitions happy.

    A. True
    
    B. False

7. If a voter chooses an alternative that is not her most preferred one because by doing so she can produce a more preferred final outcome than might otherwise be the case, then she is engaging in:

    A. sincere voting.
    
    B. strategic voting.

8. It is always the case that a researcher can determine how centralized a country is by looking at its constitution.

    A. True

    B. False
    
9. In disproportional electoral systems, the mechanical effect rewards large parties and punishes small ones.

    A. True

    B. False

10. In which of the following types of democracies would it be easier to change the current constitution?

    A. in a country with an entrenched constitution

    B. in a country with an unentrenched constitution
    
## Part III. Fill-in-the-blank {-}

1. <mark>A personalist dictatorship</mark> is one in which the leader, although often supported by a party or the military, retains personal control of policy decisions and the selection of regime personnel.

2. <mark>The dictator’s dilemma</mark> is that he relies on repression to stay in power, but this repression creates incentives for everyone to falsify their preferences so that the dictator never knows his true level of societal support.

3. <mark>The selectorate</mark> is the set of people who can play a role in selecting the leader. 

4. <mark>The winning coalition</mark> includes those people whose support is necessary for the leader to stay in power.

5. <mark>A strategic vote</mark> is a vote in which an individual votes in favor of a less preferred option because she believes doing so will ultimately produce a more preferred outcome. 

6. <mark>A sincere vote</mark> is a vote for an individual’s most preferred option.

7. <mark>An indifference curve</mark> is a set of points such that an individual is indifferent between any two points in the set.

8. <mark>The winset</mark> of some alternative *z* is the set of alternatives that will defeat *z* in a pair-wise contest if everyone votes sincerely according to whatever voting rules are being used.

9. <mark>Legislative responsibility</mark> refers to a situation in which a legislative majority has the constitutional power—a vote of no confidence—to remove a government from office without cause.

10. <mark>A political party</mark> can be thought of as a group of people that includes those who hold office and those who help get and keep them there.

## Part IV. Short answers {-}

> Short answers should be written in *short* and *clear*. I will pick two from here.

1. Explain the implication of redistribution from the median voter theorem and suggest at least one of the possible critiques against it.

2. When the winning coalition's size is small, which incentives do the leaders have for resource allocation? Why?

3. According to the selectorate theory, when are the members of the winning coalition likely to have the highest loyalty to their leader? Why?

4. According to the logic of the median voter theorem, where should we expect candidates (or parties) to locate in the policy space in two-candidate (or two-party) races? Why?

5. Explain the pros and cons of majoritarian and consensus democracies that Lijphart (2012) suggest.

6. Explain how low income class influences government policy based on power resource theory.

7. Explain the two effects of electoral laws based on Duverger's theory.

8. Explain how the size of winset affects the variance in the size of policy shifts. You can draw a picture.